# .github/workflows/ci.yml
name: Build App

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'        # speeds up installs

      - name: Install dependencies
        run: npm ci

      - name: Create .env from GitHub Secrets
        run: |
          touch .env
          {
            echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}";
            echo "VITE_GOOGLE_SHEET_ID=${{ secrets.VITE_GOOGLE_SHEET_ID }}";
            echo "VITE_RANGE_HORAIRES=${{ secrets.VITE_RANGE_HORAIRES }}";
          } >> .env

      - name: Build
        run: npm run build
